FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun db:generate

EXPOSE 3002

CMD [ "bun", "run", "index.ts" ]