FROM oven/bun:latest

WORKDIR /app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/web/package.json ./apps/web/package.json

RUN bun install

COPY ./apps/web ./apps/web

RUN bun db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun", "start:web" ]