FROM oven/bun:latest

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/backend/package.json ./apps/backend/package.json

RUN bun install

COPY ./apps/backend ./apps/backend
RUN bun db:generate

EXPOSE 3002

CMD [ "bun", "index.ts" ]